import {
  Activity,
  Award,
  BarChart3,
  BookOpen,
  Building2,
  CalendarDays,
  CheckSquare2,
  ClipboardCheck,
  Clock3,
  FileCheck2,
  FileText,
  FolderKanban,
  GraduationCap,
  KeyRound,
  Landmark,
  Layers3,
  LockKeyhole,
  MailPlus,
  MessageSquareText,
  Presentation,
  School,
  Settings2,
  ShieldCheck,
  Sparkles,
  Target,
  UserCheck,
  UsersRound,
} from "lucide-react";

import type { DashboardModuleKey } from "@/lib/dashboard/dashboard-config";

const tones = {
  blue: "bg-blue-100 text-blue-700",
  violet: "bg-violet-100 text-violet-700",
  cyan: "bg-cyan-100 text-cyan-700",
  emerald: "bg-emerald-100 text-emerald-700",
  orange: "bg-orange-100 text-orange-700",
  pink: "bg-pink-100 text-pink-700",
  indigo: "bg-indigo-100 text-indigo-700",
  slate: "bg-slate-200 text-slate-700",
};

export const dashboardModuleMeta: Record<DashboardModuleKey, { icon: typeof BookOpen; tone: string }> = {
  courses: { icon: BookOpen, tone: tones.blue },
  training: { icon: Presentation, tone: tones.violet },
  assignments: { icon: CheckSquare2, tone: tones.cyan },
  quizzes: { icon: ClipboardCheck, tone: tones.indigo },
  tests: { icon: FileText, tone: tones.pink },
  exams: { icon: FileCheck2, tone: tones.orange },
  projects: { icon: FolderKanban, tone: tones.violet },
  certificates: { icon: Award, tone: tones.emerald },
  credits: { icon: Sparkles, tone: tones.pink },
  activity: { icon: Activity, tone: tones.cyan },
  organizations: { icon: Building2, tone: tones.indigo },
  grades: { icon: BarChart3, tone: tones.orange },
  academicCourses: { icon: BookOpen, tone: tones.indigo },
  taughtCourses: { icon: Presentation, tone: tones.orange },
  sessions: { icon: CalendarDays, tone: tones.pink },
  participants: { icon: UsersRound, tone: tones.blue },
  evaluationAssignments: { icon: ClipboardCheck, tone: tones.orange },
  evaluationQuizzes: { icon: ClipboardCheck, tone: tones.indigo },
  evaluationTests: { icon: FileText, tone: tones.pink },
  evaluationProjects: { icon: FolderKanban, tone: tones.violet },
  feedback: { icon: MessageSquareText, tone: tones.emerald },
  groupsPrograms: { icon: Layers3, tone: tones.cyan },
  academicCalendar: { icon: CalendarDays, tone: tones.indigo },
  consultingSessions: { icon: MessageSquareText, tone: tones.emerald },
  clients: { icon: UserCheck, tone: tones.cyan },
  calendar: { icon: CalendarDays, tone: tones.blue },
  documents: { icon: FileText, tone: tones.slate },
  coordinatedPrograms: { icon: Target, tone: tones.violet },
  trainers: { icon: UsersRound, tone: tones.orange },
  groups: { icon: UsersRound, tone: tones.cyan },
  monitoredGroups: { icon: UsersRound, tone: tones.cyan },
  organizationGroups: { icon: UsersRound, tone: tones.cyan },
  reports: { icon: BarChart3, tone: tones.blue },
  pendingRequests: { icon: Clock3, tone: tones.orange },
  representativeStatus: { icon: UserCheck, tone: tones.emerald },
  members: { icon: UsersRound, tone: tones.blue },
  invitations: { icon: MailPlus, tone: tones.violet },
  organizationalActivity: { icon: Activity, tone: tones.cyan },
  aggregateProgress: { icon: BarChart3, tone: tones.emerald },
  organizationCertificates: { icon: Award, tone: tones.orange },
  academicStructure: { icon: Landmark, tone: tones.indigo },
  academicPrograms: { icon: GraduationCap, tone: tones.emerald },
  academicYears: { icon: CalendarDays, tone: tones.blue },
  semesters: { icon: Layers3, tone: tones.violet },
  students: { icon: UsersRound, tone: tones.cyan },
  professors: { icon: School, tone: tones.orange },
  aggregateResults: { icon: BarChart3, tone: tones.emerald },
  platformOverview: { icon: Layers3, tone: tones.indigo },
  adminAccess: { icon: KeyRound, tone: tones.violet },
  websiteSettings: { icon: Settings2, tone: tones.blue },
  usersProfiles: { icon: UsersRound, tone: tones.cyan },
  rolesPermissions: { icon: ShieldCheck, tone: tones.violet },
  security: { icon: LockKeyhole, tone: tones.emerald },
  audit: { icon: FileCheck2, tone: tones.orange },
};
